### PR TITLE
Let's make movies!

### PR DESCRIPTION
**Pull request by NoraLoose**
This adds a notebook with an example how to make movies with xmovie.

I also had to add a few packages to the conda environment to make it work.

@leticiafabre @anaclarabmariani, would any of the 2 of you like to review this pull request? If you think it looks good, we can merge it.

### CODE REVIEW

**Comment by NoraLoose** [comment]
Jupyter notebooks can be best reviewed by clicking the purple button "ReviewNB".

**Comment by anaclarabmariani** [comment]
Hi @NoraLoose, I reviewed it, but couldn't think of anything to add. I'll try to run the function and see how it goes.

**Comment by NoraLoose** [comment]
Thanks @anaclarabmariani for the review! Cool, if everything looks good you can merge the pull request. :) I think you should have permission to do so, let me know if not.

**Comment by NoraLoose** [comment]
Once this is merged, you can simply do
```
git pull upstream main 
```
and this notebook should show up on your fork.

**Comment by anaclarabmariani** [comment]
Great! I'll try to do so. But I'm having some problems merging the main repository with my copy of it.

**Pull request merged**
