### PR TITLE
Adding today tasks to the README

### PR DESCRIPTION
**Pull request by anaclarabmariani**

### CODE REVIEW

**Review by paigem — CHANGES_REQUESTED** [review]
This looks great @anaclarabmariani! Thanks for the update!

One request: could you update the gcm filters example from the tripole grid one to "Filtering on CPUs vs GPUs"? (Link: https://gcm-filters.readthedocs.io/en/latest/gpu.html) That was my bad for sending the wrong link earlier on our call!

**Review by paigem — CHANGES_REQUESTED** [review]
This looks great @anaclarabmariani! Thanks for the update!

One request: could you update the gcm filters example from the tripole grid one to "Filtering on CPUs vs GPUs"? (Link: https://gcm-filters.readthedocs.io/en/latest/gpu.html) That was my bad for sending the wrong link earlier on our call!

**Comment by anaclarabmariani** [comment]
Hi @paigem, sorry! I'll make the changes!

**Review by paigem — APPROVED** [review]
Looks good!! 😊

**Comment by paigem** [comment]
Noting also that this PR adds `hvplot` to the `.yaml` file.

**Pull request merged**
